config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "messages#index"
  resources :users, only: [:edit, :update, :show] do
    resources :gifts, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :user
  belongs_to :giver, class_name: 'User'

  validates :user_id, presence: true
  validates :giver_id, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gifts
  has_many :giftings, through: :gifts, source: :giver
  has_many :reverse_of_gifts, class_name: 'Gift', foreign_key: 'giver_id'
  has_many :receivings, through: :reverse_of_gifts, source: :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  def index
    @reciver = User.find(params[:user_id])
    # binding.pry
    @gift = Gift.new
  end

  def new
  end

  def create
    @reciver = User.find(params[:user_id])
    @gift = Gift.new(order_params)
    if @gift.valid?
      pay_item
      @gift.save
      return redirect_to root_path
    else
      render 'index'
    end
  end

  private

  def order_params
    params.require(:gift).permit(:price).merge(user_id: @reciver.id, giver_id: current_user.id)
  end

  def pay_item
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]  # PAY.JPテスト秘密鍵
    Payjp::Charge.create(
      amount: order_params[:price], # 商品の値段
      card: params[:token], # カードトークン
      currency: 'jpy'                 # 通貨の種類(日本円)
    )
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @users = User.all
    @user = User.find(params[:id])

    @all_gifts_in_table = Gift.all
    
    @giftings = []
    @all_gifts_in_table.each do |gift|
      if gift.giver_id == current_user.id
        @giftings << gift
      end
    end

    @receivings = []
    @all_gifts_in_table.each do |gift|
      if gift.user_id == current_user.id
        @receivings << gift
      end
    end
    # binding.pry
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end


# def index
#   @rooms = Room.all.order('created_at DESC')
#   @another_questions = []
#   if user_signed_in?
#     @entries = Entry.all.order('created_at DESC')
#     @questions = []
#     @question_ids = []
#     @rooms.each do |room|
#       @entries.each do |entry|
#         next unless entry.room_id == room.id
#         if entry.user_id == current_user.id
#           @questions << room
#           @question_ids << room.id
#         end
#       end
#     end
#     @another_question_ids = @rooms.ids - @question_ids
#     @rooms.each do |room|
#       @another_question_ids.each do |another_question_id|
#         @another_questions << room if room.id == another_question_id
#       end
#     end
#   else
#     @another_questions = @rooms
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gifts/index.html.erb
<%= render "shared/second-header"%>
<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      ギフティングの確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @reciver.nickname %>
        </h2>
      </div>
    </div>
    <%# /購入内容の表示 %>


    <%= form_with model: [@reciver, @gift], url: user_gifts_path, method: :post, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f|  %>
      <%= render 'shared/error_messages', model: f.object %>

      <%# カード情報の入力 %>
      <div class='credit-card-form'>
        <h1 class='info-input-haedline'>
          クレジットカード情報入力
        </h1>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">カード情報</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
          <div class='available-card'>
            <%= image_tag 'card-visa.gif', class: 'card-logo'%>
            <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
            <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
            <%= image_tag 'card-amex.gif', class: 'card-logo'%>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">有効期限</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='input-expiration-date-wrap'>
            <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
            <p>月</p>
            <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
            <p>年</p>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">セキュリティコード</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :cvc,class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
        </div>
      </div>
      <%# /カード情報の入力 %>
    
      <%# 配送先の入力 %>
      <div class='shipping-address-form'>
        <h1 class='info-input-haedline'> 
          <%# 配送先入力 %>
        </h1>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">ギフトする金額！</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :price, class:"input-default", id:"postal-code", placeholder:"ギフトしたい金額を入力してね！" %>
        </div>
      </div>  
      <%# /配送先の入力 %>
      <div class='buy-btn'>
        <%= f.submit "購入" ,class:"buy-red-btn" %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftingPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>Forte</title>
        <link rel="stylesheet" href="style.css" />
    </head>

    <body>
        <%= render "shared/header" %> 
        <h1>top page</h1>
        <div class="all-contents">
            <nav>left</nav>
            <main>
      
            <a href="#">＼！！質問する！！／</a>
            <p>--------------------あなたに関連する質問です！--------------------</p>
            
                <div class="room">
                    <div class="room-name">
                        <div class="question-title">
                          <p>question_title</p>
                        </div>
                
                        <div class="question-contents">
                       
                            <p><%= "[質問文][#{@users[0].nickname}]message.content"%></p>
                            <%= link_to "#{@users[0].nickname}にギフトする", user_gifts_path(@users[0]) %>
                            <a href="/users/<%= @users[0].id %>">
                                <%= "#{@users[0].nickname}の詳細ページ" %>
                            </a>

                            <p><%= "[回答文][#{@users[1].nickname}]message.content"%></p>
                            <%= link_to "#{@users[1].nickname}にギフトする", user_gifts_path(@users[1]) %>
                            <a href="/users/<%= @users[1].id %>">
                                <%= "#{@users[1].nickname}の詳細ページ" %>
                            </a>

                            <p><%= "----------[#{@users[2].nickname}]message.content"%></p> <%# 1つのルームにメッセージが3つ以上保存されてたら、3つ目以降も表示される！本番はいらないやつ！！！ %>
                            <%= link_to "#{@users[2].nickname}にギフトする", user_gifts_path(@users[2]) %>
                            <a href="/users/<%= @users[2].id %>">
                                <%= "#{@users[2].nickname}の詳細ページ" %>
                            </a>

                            <p><%= "----------[#{@users[3].nickname}]message.content"%></p> <%# 1つのルームにメッセージが3つ以上保存されてたら、3つ目以降も表示される！本番はいらないやつ！！！ %>
                            <%= link_to "#{@users[3].nickname}にギフトする", user_gifts_path(@users[3]) %>
                            <a href="/users/<%= @users[3].id %>">
                                <%= "#{@users[3].nickname}の詳細ページ" %>
                            </a>

                            <p><%= "----------[#{@users[4].nickname}]message.content"%></p> <%# 1つのルームにメッセージが3つ以上保存されてたら、3つ目以降も表示される！本番はいらないやつ！！！ %>
                            <%= link_to "#{@users[4].nickname}にギフトする", user_gifts_path(@users[4]) %>
                            <a href="/users/<%= @users[4].id %>">
                                <%= "#{@users[4].nickname}の詳細ページ" %>
                            </a>
                        </div>
                    </div>
                </div>
            
            <p>-----------------------------------------------------------------------------</p>
      
            
            <p>↓↓新着の質問↓↓</p>
             <div class="room">
                    <div class="room-name">
                        <div class="question-title">
                          <p>question_title</p>
                        </div>
                        <% check = 0 %>
                        <div class="question-contents">
                       
                          <% check += 1 %>
                          
                            <p>[質問文][nickname]message.content</p>
                   
                         
                            <p>[回答文][nickname]message.content</p>
                          
                            <p>----------[nickname]message.content</p> <%# 1つのルームにメッセージが3つ以上保存されてたら、3つ目以降も表示される！本番はいらないやつ！！！ %>

                        </div>
                    </div>
                </div>
            </main>
            <aside>right</aside>
        </div>

        <%= render "shared/footer" %> 
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header >
  <ul class="user-management-lists" >
    <% if user_signed_in? %>
      <li class="user-management-list" ><%= link_to current_user.nickname, edit_user_path(current_user) %></li>
      <li class="user-management-list" ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li class="user-management-list" ><%= link_to 'ログイン', new_user_session_path %></li>
      <li class="user-management-list" ><%= link_to '新規登録', new_user_registration_path %></li>
    <% end %>
  </ul>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to "トップページへ戻る", root_path %>
</header>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/second-header"%>
<%# <h2>マイページ</h2> %>
<%= "#{@user.nickname}の詳細ページ" %>

<div class="gift-action">
  <div class="gift-action-title">
    <p>自分がしたギフト</p>
  </div>
  <% @giftings.each do |gift| %>
    <div class="gift">
      <p><%= "#{@users[gift.user_id - 1].nickname}に#{gift.price}円をギフトした！" %></p>
    </div>
  <% end %>
</div>


<div class="gift-action">
  <div class="gift-action-title">
    <p>自分に送られたギフト</p>
  </div>
  <% @receivings.each do |gift| %>
    <div class="gift">

      <p><%= "#{@users[gift.giver_id - 1].nickname}から#{gift.price}円をギフトされた！感謝します！" %></p>
    </div>
  <% end %>
</div>